[package]
name = 'SatayProduct'
version = '1.0.0'

[addresses]
satay_liquidswap_automated = "0x2"

[dependencies.satay]
git = "https://github.com/satay-protocol/satay-aptos"
rev = "main"

[dependencies.Harvest]
git = "https://github.com/pontem-network/harvest"
rev = "main"